stages:
#  - test
  - deploy
  - build

#include:
# - project: 'arsh/ranthambore'
#   file: '/admin/.gitlab-ci.yml'

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: 13.233.31.22
  script:
    - ssh ubuntu@13.233.31.22 "cd ranthambore/ && git checkout main && git pull origin main && exit"
  only:
    - main

build_staging:
  stage: build
  environment:
    name: staging
    url: 13.233.31.22
  script:
    - ssh ubuntu@13.233.31.22 "cd ranthambore/ && docker-compose up --build -d"
  when: manual
  only:
    - main