package:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/package
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

payment:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/payment
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

safari:
  image: gitlab.n2rtechnologies.com:5050/arsh/ranthambore/safari
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - npm test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'